name: 部署 GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 創建重定向文件
        run: |
          mkdir -p ./HTML/Bootstrap5
          cat > ./HTML/Bootstrap5/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=Bootstrap5_Main.html">
            <title>重定向到主頁</title>
          </head>
          <body>
            <p>正在重定向到<a href="Bootstrap5_Main.html">主頁</a>...</p>
          </body>
          </html>
          EOF

      - name: 創建CNAME文件（如果需要自定義域名）
        run: |
          echo "github.pages.test.com" > ./HTML/Bootstrap5/CNAME

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: HTML/Bootstrap5
