name: 部署 GitHub Pages

on:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 檢測環境
        uses: actions/checkout@v4
      - name: 配置頁面
        uses: actions/configure-pages@v5
      - name: 創建站點目錄
        run: mkdir -p _site/HTML/Bootstrap5
      - name: Copy files
        run: cp -r HTML/Bootstrap5/* _site/HTML/Bootstrap5/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4